1.2.1 proposed
common-workflow-language/cwl-v1.2 pull request #115
Opened 2021-09-02 10:49 UTC by mr-c

A standing PR to see all the v1.2.1 proposals that have gotten initial approval

2023-07-25 20:38 UTC, kinow submitted a review, later dismissed
Thank you!

2023-08-16 17:19 UTC, adamnovak commented
I don't see anything here that raises any alarm bells for Toil.

2023-08-17 07:55 UTC, mvdbeek approved these changes
Looks good to me!

2023-08-17 18:14 UTC, DailyDreaming commented
Also looks good to me for Toil.  We'll be adding support for this soon.

2023-09-04 15:14 UTC, GlassOfWhiskey commented
[StreamFlow](https://github.com/alpha-unito/streamflow) passes all new Conformance tests. Nothing alarming in the CHANGELOG. For me, we can proceed.

2023-10-23 20:46 UTC, tetron requested changes

2023-10-23 20:46 UTC, tetron commented on CommandLineTool.yml
> +      ## Introduction to the CWL Command Line Tool draft standard v1.2.1
Since we're about to release it, we should remove the word "draft"

2023-10-23 20:46 UTC, tetron commented on CommandLineTool.yml
> +      meaning of all terms in CWL `1.2.x is the same. However, when reporting
This is slightly confusing, it should just say "Documents should continue to use `cwlVersion: v1.2`.

2023-10-23 20:46 UTC, tetron commented on CommandLineTool.yml
> +      meaning of all terms in CWL `1.2.x is the same. However, when reporting
also there's a dangling typo backtick "`1.2.x "

2023-10-23 20:46 UTC, tetron commented on CommandLineTool.yml
> +      CWL have been changed to aid the auto-generation of libraries for the reading
"Some changes ... have been changed"

2023-10-23 20:46 UTC, tetron commented on CommandLineTool.yml
> +      This specification represents the latest development draft from the
Remove "draft"

2023-10-23 20:46 UTC, tetron commented on CommandLineTool.yml
> +      as compared to CWL v1.2. v1.2.1 fixes only typos, adds clarifications,
Should be "no new features compared to v1.2.0"

2023-10-23 20:46 UTC, tetron commented on Workflow.yml
> +      "100% of CWL v1.2.1 required tests".
See comments about front text in CommandLineTool

2023-11-03 02:29 UTC, fmigneault commented
Closes https://github.com/crim-ca/weaver/issues/549

2023-11-06 16:29 UTC, tetron submitted a review, later dismissed

2023-11-07 11:32 UTC, stain commented
All good from me :+1:

2023-11-07 13:43 UTC, mvdbeek approved these changes

2023-11-12 14:32 UTC, manabuishii commented
Looks Good For Me

2023-11-12 15:30 UTC, tom-tan commented
+1!

2023-11-14 14:13 UTC, GlassOfWhiskey commented
Sorry for the delay. LGTM

2023-11-20 20:25 UTC, fabricebrito commented
@mr-c working on calrissian conformance tests this week. Will keep you posted.

2024-01-03 14:41 UTC, tetron approved these changes

2024-01-03 14:44 UTC, merged