#749 test for nested directories and initial workdir requirement
common-workflow-language/cwl-v1.2 pull request #126
Opened 2021-10-05 16:12 UTC by rupertnash

My first go at a conformance test, based on bug reported in #749

2021-10-05 16:18 UTC, mr-c requested changes
Thanks!

2021-10-05 16:18 UTC, mr-c commented on conformance_tests.yaml
> +    https://github.com/common-workflow-language/common-workflow-language/issues/749
This gets printed during test execution, so it really needs to be a single line.

Could you move the attribution into the CWL document itself? A YAML comment should be safe.

2021-10-05 16:18 UTC, mr-c commented on conformance_tests.yaml
> +  tags: [ initial_work_dir, subworkflow ]
`tags` needs at least one of `command_line_tool`, `expression_tool` or `workflow` as per https://github.com/common-workflow-language/cwl-v1.2/blob/main/CONFORMANCE_TESTS.md#tags-for-conformance-tests

2021-10-05 16:42 UTC, rupertnash commented on conformance_tests.yaml
> +    https://github.com/common-workflow-language/common-workflow-language/issues/749
Pedant in me says this is a single line, just a long one! Fixed as requested

2021-10-05 16:43 UTC, rupertnash commented
Sorry - terrible commit message! Please squash when happy!

2021-10-05 16:51 UTC, mr-c commented on conformance_tests.yaml
> +- doc: Nested directories, InitialWorkDirRequirement, and containers work together
>containers

Where? I don't see any `DockerRequirement`s. Might be good to add them, anyhow.

2021-10-06 08:48 UTC, rupertnash commented on conformance_tests.yaml
> +- doc: Nested directories, InitialWorkDirRequirement, and containers work together
That is a reasonable point, but this was not in the origin issue. (See also our discussion about leaving in the `SubworkflowFeatureRequirement` even though it is not required).

Is there a preferred list of containers to use? This workflow only needs bash so almost anything will do.

2021-10-06 08:53 UTC, mr-c commented on conformance_tests.yaml
> +- doc: Nested directories, InitialWorkDirRequirement, and containers work together
Yeah, but we should always have a container for consistency. Cloud runners will need one anyhow.

Yes, please use an existing container:
```
$ git grep dockerPull tests | awk '{print $NF}' | sed 's/"//g' | sort -u
alpine
bash:4.4.12
debian:10
debian:stable-slim
debian:stretch-slim
debian:stretch-slim,
python:2.7.15-alpine3.7
python:2-slim
python:2-slim
python:3
python:3-slim
```

2021-10-06 10:10 UTC, rupertnash commented
I literally had just committed! Do we not need to add the hint to the CommandLineTool steps?

2021-10-06 10:22 UTC, mr-c commented
> I literally had just committed!

Sorry!

> Do we not need to add the hint to the CommandLineTool steps?

We could have added them there instead, but I was feeling lazy and working from the web interface. Since we need to rebase or merge anyhow, we could move the hint down to them for simplicity.

2021-10-06 13:36 UTC, mr-c approved these changes

2021-10-06 13:36 UTC, merged