Add test for SchemaDefRequirement with a workflow and the types containing an $import statement
common-workflow-language/cwl-v1.2 pull request #171
Opened 2022-05-13 23:01 UTC by kinow

Used example written by @jeremiahsavage (thanks!). It doesn't output anything, but validates that it could import the types successfully.

Or if we prefer to test for some output, I can rewrite it to output something.

Cheers
Bruno

2022-05-14 05:16 UTC, mr-c commented
> Or if we prefer to test for some output, I can rewrite it to output something.

It would be a better test if it did output something related to the custom types, yes.

2022-05-14 05:17 UTC, kinow commented
Roger that, will keep that in mind for future PR's :-) thanks

2022-05-16 05:48 UTC, kinow commented on conformance_tests.yaml
> +    "out": "ordereddict([('CN', 'UNKNOWN'), ('DT', '1970-01-01T00:00:00Z'), ('ID', 'SRR622461'), ('LB', 'Illumina NA12878'), ('PI', '250'), ('PL', 'ILLUMINA'), ('SM', 'NA12878')])\n"
`out` here was interesting. In `tests/schemadef_types_with_import-tool.cwl` I used `valueFrom: $(self.readgroup_meta_list)` and it returned the `repr` of the ordered dict (I think).

If I used `valueFrom: $(self.readgroup_meta_list)[]` then the `ordereddict` prefix was gone :confused: 

What I wanted was to access `DT` or `ID` for the echo command. Any idea if that's doable?

2022-05-16 05:49 UTC, kinow commented on conformance_tests.yaml
> +  tags: [ workflow, schema_def ]
Not sure if I need to add `command_line_tool` because the workflow is now calling a command line too.

2022-06-21 11:39 UTC, mr-c commented on conformance_tests.yaml
> +    "out": "ordereddict([('CN', 'UNKNOWN'), ('DT', '1970-01-01T00:00:00Z'), ('ID', 'SRR622461'), ('LB', 'Illumina NA12878'), ('PI', '250'), ('PL', 'ILLUMINA'), ('SM', 'NA12878')])\n"
That's a cwltool bug, the serialization should be a pure JSON object. Can you open an issue with a reproducer?

2022-06-21 11:40 UTC, mr-c commented on conformance_tests.yaml
> +  tags: [ workflow, schema_def ]
using `command_line_tool` is a signal that no `Workflow`s are involved, so no :-)

2022-06-21 11:43 UTC, mr-c commented on tests/schemadef_types_with_import-tool.cwl
> +        valueFrom: $(self.readgroup_meta_list)
If you want the value of DT, you could try this:

```suggestion
        valueFrom: $(self.readgroup_meta_list["DT"])
```

2022-06-21 11:43 UTC, mr-c requested changes
Either the cwltool serialization bug with `ordereddict` needs fixing, or the test needs to be change to not trigger that.

2022-06-23 04:12 UTC, kinow commented on tests/schemadef_types_with_import-tool.cwl
> +        valueFrom: $(self.readgroup_meta_list)
That almost worked. But the error message displayed the `read_group_meta_list` that made me realize we had `type: array` in the input type. So `$(self.readgroup_meta_list[0]['DT'])` did the trick :+1:  thanks @mr-c !

2022-06-23 04:13 UTC, kinow commented on conformance_tests.yaml
> +    "out": "ordereddict([('CN', 'UNKNOWN'), ('DT', '1970-01-01T00:00:00Z'), ('ID', 'SRR622461'), ('LB', 'Illumina NA12878'), ('PI', '250'), ('PL', 'ILLUMINA'), ('SM', 'NA12878')])\n"
Creating the smallest example to reproduce the issue, then will create the issue (and maybe a PR too).

2022-06-23 08:18 UTC, kinow commented on conformance_tests.yaml
> +    "out": "ordereddict([('CN', 'UNKNOWN'), ('DT', '1970-01-01T00:00:00Z'), ('ID', 'SRR622461'), ('LB', 'Illumina NA12878'), ('PI', '250'), ('PL', 'ILLUMINA'), ('SM', 'NA12878')])\n"
Issue: https://github.com/common-workflow-language/cwltool/issues/1684

2022-06-23 08:20 UTC, kinow commented
Created `cwltool` issue, and the test output was updated. Ready for review again :+1:

2022-06-23 08:21 UTC, mr-c approved these changes

2022-06-23 08:21 UTC, merged

2022-06-23 08:21 UTC, mr-c commented
Thanks!