Fixes #193
common-workflow-language/cwl-v1.2 pull request #235
Opened 2023-04-17 21:02 UTC by GlassOfWhiskey

2023-04-17 21:30 UTC, GlassOfWhiskey commented
Here automated preview fails because
```
fatal: destination path '/opt/build/repo/temp//cwl-website' already exists and is not an empty directory.
```
It seems not related to the PR, but with something weird in the CI file system

2023-04-18 06:10 UTC, mr-c commented on tests/iwd/test-index.yaml
> +  doc: "Test the use of symlinks in the InitialWorkDirRequirement"
Where is the symlink?

2023-04-18 06:41 UTC, GlassOfWhiskey commented on tests/iwd/test-index.yaml
> +  doc: "Test the use of symlinks in the InitialWorkDirRequirement"
In the implementation, and in the title of the issue XD

2023-04-18 07:01 UTC, mr-c commented on tests/iwd/test-index.yaml
> +  doc: "Test the use of symlinks in the InitialWorkDirRequirement"
Cwltool might be using a symlink, but that doesn't mean that other implementations would.

https://github.com/common-workflow-language/cwltool/issues/1029 outlines a more robust test

2023-04-18 07:16 UTC, GlassOfWhiskey commented on tests/iwd/test-index.yaml
> +  doc: "Test the use of symlinks in the InitialWorkDirRequirement"
That test is exactly what I implemented here, just removing unnecessary parts and splitting CLTs.
If you want we can rename symlinks to another thing, but symlinks are not present in the original test, neither.

2023-04-18 07:29 UTC, mr-c commented on tests/iwd/test-index.yaml
> +  doc: "Test the use of symlinks in the InitialWorkDirRequirement"
I see, thanks. Yes, the description needs updating. Can you confirm that this conformance test triggers the same bug in the old version of cwltool?

2023-04-21 11:01 UTC, GlassOfWhiskey commented
Anything to do here?

2023-04-21 13:54 UTC, mr-c requested changes

2023-04-21 13:54 UTC, mr-c commented on tests/iwd/test-index.yaml
> +  doc: "Test the use of symlinks in the InitialWorkDirRequirement"
Please remove the word `symlink` from this PR, unless you want to mention that cwltool had a bug related to complicated IWDRs & its internal use of symlinks

2023-04-21 19:45 UTC, mr-c approved these changes

2023-04-21 19:49 UTC, merged