Update run test.sh
common-workflow-language/cwl-v1.2 pull request #72
Opened 2020-12-05 18:25 UTC by tom-tan

This request fixes #70.

Basically it copies `run_test.sh` in [common-workflow-language/common-workflow-language](https://github.com/common-workflow-language/common-workflow-language) but includes several minor changes:

- delete `DRAFT` stuff
- introduce `CWL_VER` but only used in the message in `runtest` function
- fix `--self` to check `tests` directory recursively

I confirmed that `--timeout` (only positive cases), `--self` (checked it recursively validates the documents), `--badgedir` and `--tags` work correctly.

2020-12-05 20:53 UTC, mr-c approved these changes

2020-12-05 20:56 UTC, mr-c requested changes
Thanks!

shellcheck suggests the following:

```
In run_test.sh line 105:
    for target in $(find tests -type f -name "*.cwl"); do
                  ^-- SC2044: For loops over find output are fragile. Use find -exec or a while read loop.


In run_test.sh line 107:
        if [[ $? -ne 0 ]]; then echo "[INVALID] ${target}" && exit 1; fi
              ^-- SC2181: Check exit code directly with e.g. 'if mycmd;', not indirectly with $?.


In run_test.sh line 123:
    if [ "$?" != "0" ]; then
         ^--^ SC2181: Check exit code directly with e.g. 'if mycmd;', not indirectly with $?.

For more information:
  https://www.shellcheck.net/wiki/SC2044 -- For loops over find output are fr...
  https://www.shellcheck.net/wiki/SC2181 -- Check exit code directly with e.g...
```

2020-12-06 03:53 UTC, tom-tan commented
Done!

2020-12-06 07:56 UTC, mr-c approved these changes

2020-12-06 07:56 UTC, merged