Add test to ensure a synthetic file is created properly.
common-workflow-language/cwl-v1.2 pull request #88
Opened 2020-12-22 08:35 UTC by DailyDreaming

Adds a basic test to check that a file generated with inline contents exists and has the expected contents (using `cat`).

Based on https://github.com/common-workflow-language/cwltool/issues/369 .

2020-12-22 09:19 UTC, tom-tan commented on conformance_tests.yaml
> +      "basename": "684051cefdffc63ea1be04442fe133c803d86cbe",
`basename` and `nameext` should not be checked because they are implementation dependent values.

2020-12-22 15:20 UTC, DailyDreaming commented on conformance_tests.yaml
> +      "basename": "684051cefdffc63ea1be04442fe133c803d86cbe",
Should be resolved.

2020-12-22 15:59 UTC, tom-tan requested changes

2020-12-22 15:59 UTC, tom-tan commented on tests/synth-file.cwl
> +cwlVersion: v1.0
Fix the version to v1.2 as follows:
```suggestion
cwlVersion: v1.2
```

2020-12-22 23:00 UTC, DailyDreaming commented on tests/synth-file.cwl
> +cwlVersion: v1.0
Fixed, thanks for the catch!

2020-12-23 00:53 UTC, tom-tan approved these changes

2020-12-30 13:46 UTC, merged